# Generated by Django 4.0.4 on 2022-08-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0012_receiptdetails_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('quantity_added', models.CharField(max_length=225)),
            ],
        ),
    ]
