# Generated by Django 4.0.4 on 2022-08-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0013_stockgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('units', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
