# Generated by Django 4.0.4 on 2022-08-30 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0015_stockitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='stockgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockgroup'),
        ),
    ]
