# Generated by Django 4.0.4 on 2022-08-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0016_stockitems_stockgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockmonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openbalance_quantity', models.IntegerField(default=0)),
                ('openbalance_value', models.IntegerField(default=0)),
                ('particular', models.CharField(max_length=225)),
                ('inwards_quantity', models.IntegerField(default=0)),
                ('inwards_value', models.IntegerField(default=0)),
                ('outwards_quantity', models.IntegerField(default=0)),
                ('outwards_value', models.IntegerField(default=0)),
                ('closing_quantity', models.IntegerField(default=0)),
                ('closing_value', models.IntegerField(default=0)),
                ('stockitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockitems')),
            ],
        ),
    ]
