# Generated by Django 4.0.4 on 2022-08-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0017_stockmonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockvoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('particular', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('vch_no', models.IntegerField(default=0)),
                ('inwards_qty', models.IntegerField(default=0)),
                ('inwards_value', models.IntegerField(default=0)),
                ('outwards_qty', models.IntegerField(default=0)),
                ('outwards_value', models.IntegerField(default=0)),
                ('stockmonth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockmonthly')),
            ],
        ),
    ]
