# Generated by Django 4.0.4 on 2022-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0018_stockvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmonthly',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
