# Generated by Django 4.0.4 on 2022-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0019_stockmonthly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonthly',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
