# Generated by Django 4.0.4 on 2022-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0020_alter_stockmonthly_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockmonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=225)),
            ],
        ),
    ]
