# Generated by Django 4.0.4 on 2022-08-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0021_stockmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmonthly',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockmonths'),
        ),
        migrations.AddField(
            model_name='stockvoucher',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockmonths'),
        ),
    ]
