# Generated by Django 4.0.4 on 2022-09-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0022_stockmonthly_month_stockvoucher_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthwise_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inwards_quantity', models.IntegerField(default=0)),
                ('inwards_value', models.IntegerField(default=0)),
                ('outwards_quantity', models.IntegerField(default=0)),
                ('outwards_value', models.IntegerField(default=0)),
                ('closing_quantity', models.IntegerField(default=0)),
                ('closing_value', models.IntegerField(default=0)),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockmonths')),
                ('stockmonth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockmonthly')),
            ],
        ),
    ]
