# Generated by Django 4.0.4 on 2022-09-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0023_monthwise_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthwise_stock',
            name='stockmonth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.stockmonthly'),
        ),
    ]
